[PROTOCOLS]
Virtual Screening = [
    {"tag": "section", "text": "Preparation", "icon": "bookmark.png", "children": [
	    {"tag": "protocol_group", "text": "Ligand Preparation", "openItem": "False", "children": [
	        {"tag": "protocol", "value": "ProtChemGypsumDL",   "text": "default"}
	    ]}
	]},
    {"tag": "section", "text": "Lead optimization", "icon": "bookmark.png", "children": [
        {"tag": "protocol", "value": "ProtChemAutoGrow4",   "text": "default"},
        {"tag": "protocol", "value": "ProtChemDeepFrag",   "text": "default"}
	]}
    ]
